apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mycorpus
  namespace: miraiku
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - mycorpus.fake-domain.name
      secretName: mycorpus-tls
  rules:
    - host: mycorpus.fake-domain.name
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: myrag-backend
                port:
                  number: 8200
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: myrag-backend
                port:
                  number: 8200
          - path: /graph
            pathType: Prefix
            backend:
              service:
                name: myrag-backend
                port:
                  number: 8200
          - path: /articles
            pathType: Prefix
            backend:
              service:
                name: myrag-backend
                port:
                  number: 8200
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myrag-frontend
                port:
                  number: 3000
