apiVersion: v1
kind: Service
metadata:
  name: myrag-backend
  namespace: miraiku
spec:
  selector:
    app: myrag-backend
  ports:
    - name: http
      port: 8200
      targetPort: 8200
      protocol: TCP
